name: ${project.name}
author: cptingle
main: com.cptingle.MCAdmin.MCAdmin
version: ${project.version}
api-version: 1.15
commands:
    mca:
        description: Base command for MCAdmin
        usage: Error
    mcadmin:
        description: Base command for MCAdmin
        usage: Error
    ban:
        description: 'Usage: /ban <player> [message]'
    unban:
        description: 'Usage: /unban <player>'
    pardon:
        description: 'Usage: /pardon <player>'
permissions:
    mcadmin.register:
        description: Allows a player to register
        default: op
    mcadmin.ban:
        description: Bans specified player
        default: op
    mcadmin.pardon:
        description: Unbans specific player
        default: op
  
        
