name: ${project.name}
author: cptingle
main: com.cptingle.MCAdmin.MCAdmin
version: ${project.version}
api-version: 1.15
commands:
    mca:
        description: Base command for MCAdmin
        usage: Error
    mcadmin:
        description: Base command for MCAdmin
        usage: Error
permissions:
    mcadmin.register:
        description: Allows a player to register
        default: true
  
        
